<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\AeroTrip_Login_Register\.git\**" />
    <Content Remove="wwwroot\AeroTrip_Login_Register\.git\**" />
    <EmbeddedResource Remove="wwwroot\AeroTrip_Login_Register\.git\**" />
    <None Remove="wwwroot\AeroTrip_Login_Register\.git\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.26">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.23" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="8.1.4" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="8.1.4" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="8.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\AeroTripProject.Application\AeroTripProject.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\AeroTripProject.Infrastructure\AeroTripProject.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Infrastructure\AeroTripProject.Persistence\AeroTripProject.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Member\Data\" />
    <Folder Include="wwwroot\userimages\" />
  </ItemGroup>

</Project>
